# Generated by Django 5.1.4 on 2025-04-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAlquimia', '0004_shipping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
