# Generated by Django 5.1.4 on 2025-04-29 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAlquimia', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
