# Generated by Django 5.1.4 on 2025-05-05 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAlquimia', '0007_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('metodo_envio', models.CharField(choices=[('D', 'Domicilio'), ('S', 'Sucursal')], max_length=1, null=True)),
                ('codigo_postal_destino', models.CharField(blank=True, max_length=10)),
                ('direccion_envio', models.TextField(blank=True)),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('numero_seguimiento', models.CharField(blank=True, max_length=50)),
                ('customer_id', models.CharField(blank=True, max_length=20)),
                ('ext_order_id', models.CharField(blank=True, max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
