# Generated by Django 5.1.4 on 2025-05-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAlquimia', '0008_pedido_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
