# Generated by Django 5.1.4 on 2025-05-05 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAlquimia', '0009_remove_perfilusuario_usuario_delete_pedido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='height',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='length',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='producto',
            name='weight',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='producto',
            name='width',
            field=models.IntegerField(default=20),
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micorreo_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('ext_order_id', models.CharField(max_length=100, unique=True)),
                ('delivery_type', models.CharField(choices=[('D', 'Domicilio'), ('S', 'Sucursal')], max_length=1)),
                ('agency_code', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code_origin', models.CharField(max_length=20)),
                ('postal_code_destination', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.IntegerField()),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
