# Generated by Django 5.1.4 on 2025-05-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAlquimia', '0010_producto_height_producto_length_producto_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='height',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='length',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='width',
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
