# Generated by Django 5.1.4 on 2025-05-06 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAlquimia', '0011_remove_producto_height_remove_producto_length_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alto_cm',
            field=models.IntegerField(default=10, help_text='Alto en centímetros (máx 150)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho_cm',
            field=models.IntegerField(default=10, help_text='Ancho en centímetros (máx 150)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='largo_cm',
            field=models.IntegerField(default=10, help_text='Largo en centímetros (máx 150)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_gramos',
            field=models.IntegerField(default=100, help_text='Peso en gramos (1-25000)'),
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micorreo_shipping_id', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_entrega', models.CharField(choices=[('D', 'Domicilio'), ('S', 'Sucursal')], max_length=1)),
                ('sucursal_codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_total', models.IntegerField(help_text='Peso total en gramos')),
                ('alto_total', models.IntegerField(help_text='Alto total en centímetros')),
                ('ancho_total', models.IntegerField(help_text='Ancho total en centímetros')),
                ('largo_total', models.IntegerField(help_text='Largo total en centímetros')),
                ('codigo_postal_origen', models.CharField(max_length=10)),
                ('codigo_postal_destino', models.CharField(max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('carrito', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micorreo_customer_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('direccion_calle', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_numero', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion_piso', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion_departamento', models.CharField(blank=True, max_length=10, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_provincia', models.CharField(blank=True, help_text='Código de provincia (ej. B para Buenos Aires)', max_length=1, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
