# Generated by Django 5.1.4 on 2025-05-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAlquimia', '0012_producto_alto_cm_producto_ancho_cm_producto_largo_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='codigo_provincia',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='micorreo_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
