# Generated by Django 5.1.4 on 2025-05-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAlquimia', '0013_alter_perfilusuario_codigo_provincia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='codigo_provincia',
            field=models.CharField(blank=True, help_text='Código de provincia (ej. B para Buenos Aires)', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='micorreo_customer_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
