# Generated by Django 5.1.4 on 2025-05-06 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAlquimia', '0014_alter_perfilusuario_codigo_provincia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='producto',
            name='alto_cm',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ancho_cm',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='largo_cm',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_gramos',
            field=models.IntegerField(default=1000),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micorreo_customer_id', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Envio',
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
